### PR TITLE
changed from cordova light to normal cordova app

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [RHMAP-7727](https://issues.jboss.org/browse/RHMAP-7727)

### CODE REVIEW

**Comment by flashlee** [comment]
@edewit need to add 'plugins' folder. fh-digger-cli will not resolve this template as advanced hybrid project without this directory

**Comment by edewit** [comment]
@flashlee changed that in digger-cli https://github.com/fheng/fh-digger-cli/pull/16

**Comment by secondsun** [comment]
@edewit It works in the preview, but when I run it on a device I get this error : "App init returned error : 404 - ", source: file:///android_asset/www/main.js (15098)

**Comment by secondsun** [comment]
Ok, @edewit helped me with my error.  +1

**Comment by secondsun** [comment]
Landed

**Pull request merged**
